#! /bin/sh

# set e: exit if something fails; set u: exit if a variable is unset
set -eu

# Declare variables:
unset FORCE_DAYS PLAYLIST_FILE DEBUG
readonly SERVERPATH="http://live.ber.c3voc.de:7999/"
readonly RTMPPATH="rtmp://ingest.c3voc.de/stream/"
readonly RED='\033[0;31m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m' # No Color
readonly UNDERLINED='\033[4m'
readonly PROGNAME="${0##*/}"
VERBOSITY=0
ALL=false
FORCE=false

# Verbose messages
verbose() {
	msg="${1}"
	level="${2:-1}"
	i=0

	if [ ${level} -le ${VERBOSITY} ]; then
		while [ ${i} -lt ${level} ]; do
      if [ -n "${DEBUG-}" ]; then
        printf "${RED}=${NC}\n" >&2
      else
        printf "=" >&2
      fi
			i=$(( ${i} + 1 ))
		done
    if [ -n "${DEBUG-}" ]; then
  		echo "${RED}> ${msg}${NC}" >&2
    else
  		echo "> ${msg}" >&2
    fi
	fi
}

# Short manual
manual()
{
  echo "Usage: ${PROGNAME} [-a | -d | -D | -f | -h | -k | -p ${UNDERLINED}file${NC} | -v]"
  echo "       opens mpv with all active voc streams"
  echo "       -a tries to open all streams listed in 'complete-playlist.m3u8'"
  echo "       -d debug mode: print commands and arguments while executed"
  echo "       -D debug mode: print script lines while read"
  echo "       -f tries to open all active and planned streams"
  echo "       -h shows this help"
  echo "       -k shows shortcuts"
  echo "       -p use playlist ${UNDERLINED}file${NC} in format m3u8"
  echo "       -v increases verbosity"
  exit
}

# Show extracted shortcuts from input.conf
keys()
{
  echo "Shortcuts:"
  grep '^[[:blank:]]*[^[:blank:]#]' input.conf
  verbose "grep shortcuts from 'input.conf': $?" 2
  exit
}

# Cleanup on exit
cleanup ()
{
  # Delete the current playlist if exists
  verbose "Cleanup on exit" 2
  PLAYLIST="current-playlist.m3u8"
  if [ -e "$PLAYLIST" ]; then
    rm "$PLAYLIST"
    verbose "Delete 'current-playlist.m3u8': $?" 2
  fi
  exit
}

# Check options
while getopts 'adDf:hkp:v' option 2>/dev/null; do
  case $option in
    a ) ALL=true;;
    d ) set -x
        DEBUG=true;;
    D ) set -v
        DEBUG=true;;
    f ) FORCE_DAYS="${OPTARG}"
        FORCE=true;;
    h ) manual;;
    k ) keys;;
    p ) PLAYLIST_FILE="${OPTARG}";;
    v ) VERBOSITY=$(( ${VERBOSITY} + 1 ));;
    * ) if [ $1 != "-?" ]; then
          curropt=$(($OPTIND - 1))
          eval "curropt=\$$curropt"
          printf "%b\n" "${YELLOW}Warning: illegal option ${curropt}${NC}" 1>&2
        fi
        manual;;
  esac
done
verbose "${YELLOW}Note: number after colon usually represents commands exit code${NC}"
verbose "Level of verbosity: $VERBOSITY"

# Exit handler
trap cleanup 0 1 2 3 6

# Choose the playlist
if [ $ALL = true ]; then
  # This playlist has all servers
  PLAYLIST="complete-playlist.m3u8"
  verbose "Used playlist: $PLAYLIST"
  if [ ! -f "$PLAYLIST" ]; then
    printf "%b\n" "${YELLOW}Warning: playlist '$PLAYLIST' with all servers does not exist${NC}" 1>&2
    exit 1
  fi
elif [ -n "${PLAYLIST_FILE-}" ]; then
  PLAYLIST="${PLAYLIST_FILE}"
  verbose "Used playlist: $PLAYLIST"
  if [ ! -f "$PLAYLIST" ]; then
    printf "%b\n" "${YELLOW}Warning: playlist '$PLAYLIST' does not exist${NC}" 1>&2
    exit 1
  fi
else
  # This playlist should have only servers found in https://streaming.media.ccc.de/streams/v2.json and will be created
  PLAYLIST="current-playlist.m3u8"
  verbose "Used playlist: $PLAYLIST"

  # Read current active streams by api json
  verbose "Read stream api with option forceopen=1: $FORCE"
  if [ $FORCE = true ]; then
    # with option forceopen=1 (shows all streams done, running and planned)
    JSON="$(curl https://streaming.media.ccc.de/streams/v2.json?forceopen=1 2>/dev/null)"
    verbose "Curl json: $?" 2
  else
    # shows only running streams
    JSON="$(curl https://streaming.media.ccc.de/streams/v2.json 2>/dev/null)"
    # JSON="$(cat xtemp/example.json 2>/dev/null)"
    verbose "Curl json: $?" 2
  fi
  verbose "Stream api json:\n$JSON" 4

  # Check if trimmed (all white spaces) $JSON is empty
  if [ "$(echo "$JSON" | tr -d "[:blank:]")" = "[]" ] && [ $ALL = false ]; then
    printf "%b\n" "${YELLOW}Warning: no active streams available${NC}" 1>&2
    exit 1
  fi

  # Find all streaming servers in $JSON, trim to server only
  # source: https://stackoverflow.com/questions/10586153/split-string-into-an-array-in-bash/13196466
  REGEX="\"stream\": \".+\""
  SERVER="$(echo "$JSON" | grep -oE "$REGEX")"
  verbose "Grep '$REGEX' from json: $?" 2
  SERVER="$(echo "$SERVER" | sed 's/"stream": "//g')"
  verbose "Clear result before servers: $?" 2
  SERVER="$(echo "$SERVER" | sed 's/"//g')"
  verbose "Clear result after servers: $?" 2
  SERVER="$(echo "$SERVER" | sort)"
  verbose "Sort servers: $?" 2
  SERVER="$(echo "$SERVER" | uniq)"
  verbose "Shrink to unique servers: $?" 2
  verbose "Extracted servers:\n$SERVER" 3

  # Create playlist
  # Playlist header
  echo "#EXTM3U" > $PLAYLIST
  echo "#EXT-X-VERSION:3" >> $PLAYLIST
  # Repeat playlist names and servers and "#EXT-X-DISCONTINUITY"
  for STREAM in $SERVER
  do
      # Write servers name as info into playlist
      echo "#EXTINF:0,$STREAM" >> $PLAYLIST
      # If servers first letter is "q" write it as an rtmp server
      if [ "$(echo "$STREAM" | head -c1)" = "q" ]; then
        echo "$RTMPPATH$STREAM" >> $PLAYLIST
        verbose "Add $RTMPPATH$STREAM to playlist: $?" 3
      # Write normal server with http into playlist
      else
        echo "$SERVERPATH$STREAM" >> $PLAYLIST
        verbose "Add $SERVERPATH$STREAM to playlist: $?" 3
      fi
      # Write playlist divider
      echo "#EXT-X-DISCONTINUITY" >> $PLAYLIST
  done
  {
    # Set a picture as last server, so mpv will not end by accident
    echo "#EXTINF:0,end of list"
    echo "voctocat.png"
    # End of playlist
    echo "#EXT-X-ENDLIST"
  } >> $PLAYLIST
  verbose "Playlist complete: $?"
fi

# That is really playing
mpv $PLAYLIST \
  --fs \
  --no-ytdl \
  --msg-level=all=error,ffmpeg=fatal \
  --no-input-default-bindings \
  --config-dir=. \
  --load-scripts=no \
  --scripts=select-audio.lua:select-video.lua:select-venue.lua \
  --force-window=immediate \
  --keep-open=always \
  --idle=yes \
  --vd-lavc-show-all=yes \
  --no-initial-audio-sync \
  --audio-stream-silence=yes \
  --demuxer-cache-wait=no \
  --screenshot-format=png \
  --script-opts=osc-visibility=always \
  --osd-duration=5000 \
  --osd-msg1="room: 1 – 0       audio: q, w, e - Native, Translated, Translated-2       video: y, x - HD, Slides" \
  --no-osd-bar \
  --osd-font-size=30 \
  --osd-spacing=1 \
  --osd-border-size=1 \
  --osd-margin-x=10 \
  --osd-margin-y=4

verbose "Exit"
exit
