\" SPDX-FileCopyrightText: 2020 Simpel <stream-observer@simpel.cc>
\"
\" SPDX-License-Identifier: MIT
.Dd May 03, 2020              \" DATE
.Dt STROBS 1      \" Program name and manual section number
.Os
.Sh NAME                 \" Section Header - required - don't modify
.Nm STROBS
.Nd a script to observe running voc video streams.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl d
.Op Fl D
.Op Fl f
.Op Fl h
.Op Fl j
.Op Fl k
.Op Fl m
.Op Fl n
.Op Fl p Ar file              \" [-p file]
.Op Fl s
.Op Fl t
.Op Fl v
.Op Fl V
.Op Fl x
.Sh DESCRIPTION          \" Section Header - required - don't modify
The
.Nm
script opens mpv with all active (currently streaming) streams from Chaos
Computer Club made by VOC (video operation center) in a playlist as found at
.Mt https://streaming.media.ccc.de.
.Me
Optionally it can also try to open all streams given in a valid playlist.

.Sh OPTIONS
.Bl -tag -width "-p file" -indent  \" Begins a tagged list
.It Fl d
debug mode: print commands and arguments while executed
.It Fl D
debug mode: print script lines while read
.It Fl f
forces (with -p / -j) open playlist / download full json
.It Fl h
help shown
.It Fl j
json export to disk
.It Fl k
keys/shortcuts shown
.It Fl m
man page shown
.It Fl n
name stream with technical extension (e.g. s23)
.It Fl p Ar file
playlist
.Ar file
with servers in format m3u8
.It Fl s
sort server list alphanumerical
.It Fl t
timetable of running and coming events shown
.It Fl v
verbosity increasing with
.Ar v
.It Fl V
version print
.It Fl x
exit before mpv; keeps current-playlist.m3u8
.El
.Sh DETAILS
.Nm
downloads
.Mt http://live.ber.c3voc.de:7999/status-json.xsl
.Me
and searches for active (current streaming) streams. It reads then
.Mt https://streaming.media.ccc.de/streams/v2.json
.Me
and extracts end time of the streams and their display names. With this
informations it builds a playlist in m3u8 format and starts mpv with this playlist.
.Sh EXAMPLES
The command:
.Pp
.Dl "strobs"
.Pp
opens current streams in mpv.
.Pp
The command:
.Pp
.Dl "strobs -p 36c3.m3u8 -s"
.Pp
uses the playlist
.Ar 36c3.m3u8
for mpv. In addition it will sort the streams alphanumerical.
.Pp
The command:
.Pp
.Dl "strobs -j -f"
.Pp
will download and save
.Ar status_liveber.xsl
,
.Ar status_ingest.xsl
,
.Ar current.json
and exit before opening mpv. In addition it will save json including past events.
.Pp
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "./current-playlist.m3u8   "
.It Pa current-playlist.m3u8
generated playlist while running
.It Pa input.conf
user-defined key bindings for mpv
.It Pa keys.lua
key bindings for audio, video and rooms
.It Pa strobs
shell script to execute
.It Pa strobs.1
this man page
.It Pa voctocat.gif
temp playlist item so mpv does not stop
.El                      \" Ends the list
.Sh HISTORY           \" Document history if command behaves in a unique manner
.Nm
was written by Simpel <git@simpel.cc> in April 2020.
.Sh BUGS              \" Document known, unremedied bugs
Please file bugs and feature requests by emailing the author
or opening issues at
.Mt https://github.com/SimpelMe/stream-observer
.Me
